[package]
name = "gpucanvas"
description = "Antialiased 2D vector drawing library"
version = "0.1.0"
license = "MIT/Apache-2.0"
readme = "README.md"
authors = ["Peter Todorov <ptodorov@cytec.bg>"]
keywords = ["graphics", "canvas", "vector", "drawing", "gpu"]
categories = ["graphics"]
repository = "https://github.com/cytecbg/gpucanvas"
edition = "2018"

[dependencies]
fnv = "1.0.6"
rgb = "0.8.16"
libc = "0.2.68"
imgref = "1.4.0"
bitflags = "1.2.1"
ttf-parser = "0.3.0"
harfbuzz_rs = "1.0.1"
unicode-bidi = "0.3.4"
unicode-script = "0.5.0"
generational-arena = "0.2.7"
lru = { version = "0.4.3", default-features = false }
image = { version = "0.23.2", optional = true }

# metal features
metal = "*"
memoffset = "*"
metalgear = { git = "https://github.com/adamnemecek/metalgear" }
static_assertions = "*"

[features]
default = ["image-loading"]
image-loading = ["image"]

[build-dependencies]
gl_generator = "0.14.0"
pkg-config = "0.3.17"

[dev-dependencies]
glutin = "0.22.0"
euclid = "0.20.7"
rand = "0.7"
svg = "0.6.0"
usvg = "0.9.0"
